spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  jackson:
#    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
  port: 8080
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /log/sell/
#  file: /log/sell/sell.log
#  level:
#    root: debug

